// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package models

import (
	"database/sql"
)

type Author struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Bio  string `json:"bio"`
}

type Book struct {
	ID       int64         `json:"id"`
	Name     string        `json:"name"`
	AuthorID sql.NullInt32 `json:"author_id"`
}
